export const TOGGLE_LEFT_SIDEBAR = "TOGGLE_LEFT_SIDEBAR"

export const userTypes = {
    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
    USER_LOGOUT: 'USER_LOGOUT',
};