export const TOGGLE_LEFT_SIDEBAR = "TOGGLE_LEFT_SIDEBAR"

export const userTypes = {

    // Login
    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

    // Logout
    USER_OUT_REQUEST: 'USER_OUT_REQUEST',
    USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
    USER_LOGOUT_FAILURE: 'USER_LOGIN_FAILURE',

    // User
    SET_USER: 'SET_USER',
    REMOVE_USER: 'REMOVE_USER',

};